main:
    input_folder: inputs
    output_folder: outputs
    outputModule: "outputGenerator1"
    inputModule: "numberGenerator"

numberGenerator:
    numberOfFiles: 10
    seed: 4864645
    maxValue: 10
    valuesPerFiles: 100000